import { formatCurrency } from "@/lib/utils/format";

// One description of a bill, shared by the till (straight after a sale) and
// Sales history (reopening an old one), so a reprint matches the original.

export interface InvoiceLine {
  key: string;
  name: string;
  description?: string;
  quantity: number;
  unitPrice: number;
  discount: number;
  total: number;
}

export interface InvoicePrescription {
  right: { sph: number | string; cyl: number | string; axis: number | string; pd: number | string; add: number | string };
  left: { sph: number | string; cyl: number | string; axis: number | string; pd: number | string; add: number | string };
  isOwn: boolean;
}

// Comes from Settings → Shop, so changing the address there changes every
// bill. It used to be typed into the receipt itself, which is why the old
// Tariq Road address kept printing after the shop's address was updated.
export interface ShopDetails {
  name: string;
  address: string;
  phone: string;
  ntn: string;
  footer: string;
}

export interface InvoiceData {
  invoiceNo: string;
  date: string;
  orderTakenBy: string;
  billGeneratedBy: string;
  customerName: string | null;
  customerPhone: string;
  lines: InvoiceLine[];
  subtotal: number;
  discount: number;
  total: number;
  paymentMethod: string;
  paymentStatus: string;
  paid: number;
  balance: number;
  // Money taken after the sale (an advance settled later), printed on the
  // reissued bill so the customer can see how the total was made up.
  payments?: { date: string; amount: number; method: string }[];
  prescription: InvoicePrescription | null;
}

const v = (x: number | string) => (x === "" ? 0 : x);

export function ThermalReceipt({ invoice, shop }: { invoice: InvoiceData; shop: ShopDetails }) {
  const rx = invoice.prescription;
  return (
    <div className="receipt-paper mx-auto rounded-lg shadow-lg">
      <div className="text-center border-b border-dashed border-gray-400 pb-2 mb-2">
        <img src="/eyespy-logo-black.png" alt={shop.name} className="h-10 w-auto mx-auto mb-1.5" />
        {shop.address && <p className="text-[11px]">{shop.address}</p>}
        {shop.phone && <p className="text-[11px]">Ph: {shop.phone}</p>}
        {shop.ntn && <p className="text-[11px]">NTN: {shop.ntn}</p>}
      </div>
      <p className="text-[11px]">INV: {invoice.invoiceNo}</p>
      <p className="text-[11px]">Date: {invoice.date}</p>
      {invoice.orderTakenBy && <p className="text-[11px]">Order taken by: {invoice.orderTakenBy}</p>}
      {invoice.billGeneratedBy && <p className="text-[11px]">Bill generated by: {invoice.billGeneratedBy}</p>}
      {invoice.customerName && <p className="text-[11px]">Customer: {invoice.customerName}</p>}
      {rx && (
        <div className="text-[11px] mt-1 pt-1 border-t border-dashed border-gray-400">
          <p className="font-medium">Prescription{rx.isOwn ? " (Customer's Own)" : ""}</p>
          <p>OD: SPH {v(rx.right.sph)} CYL {v(rx.right.cyl)} AXIS {v(rx.right.axis)} PD {v(rx.right.pd)} ADD {v(rx.right.add)}</p>
          <p>OS: SPH {v(rx.left.sph)} CYL {v(rx.left.cyl)} AXIS {v(rx.left.axis)} PD {v(rx.left.pd)} ADD {v(rx.left.add)}</p>
        </div>
      )}
      <div className="border-t border-dashed border-gray-400 mt-2 pt-2">
        {invoice.lines.map((line) => (
          <div key={line.key} className="mb-1">
            <p className="text-[11px] font-medium">{line.name}</p>
            {line.description && <p className="text-[10px] leading-snug">{line.description}</p>}
            <div className="flex justify-between text-[11px]">
              <span>{line.quantity} x {formatCurrency(line.unitPrice)}</span>
              <span>{formatCurrency(line.total)}</span>
            </div>
            {line.discount > 0 && (
              <p className="text-[11px] text-right">Disc: -{formatCurrency(line.discount)}</p>
            )}
          </div>
        ))}
      </div>
      <div className="border-t border-dashed border-gray-400 mt-2 pt-2 space-y-0.5">
        <div className="flex justify-between text-[11px]"><span>Subtotal</span><span>{formatCurrency(invoice.subtotal)}</span></div>
        {invoice.discount > 0 && (
          <div className="flex justify-between text-[11px]"><span>Discount</span><span>-{formatCurrency(invoice.discount)}</span></div>
        )}
        <div className="flex justify-between text-sm font-bold border-t border-dashed border-gray-400 pt-1 mt-1">
          <span>TOTAL</span><span>{formatCurrency(invoice.total)}</span>
        </div>
        <p className="text-[11px]">Payment: {invoice.paymentMethod} ({invoice.paymentStatus})</p>
        {(invoice.payments?.length ?? 0) > 0 && (
          <div className="text-[11px] border-t border-dashed border-gray-400 mt-1 pt-1">
            <p className="font-medium">Payments received</p>
            <div className="flex justify-between">
              <span>Advance ({invoice.paymentMethod})</span>
              <span>{formatCurrency(invoice.paid - invoice.payments!.reduce((s, p) => s + p.amount, 0))}</span>
            </div>
            {invoice.payments!.map((p, i) => (
              <div key={i} className="flex justify-between">
                <span>{new Date(p.date).toLocaleDateString("en-PK", { day: "2-digit", month: "short" })} ({p.method})</span>
                <span>{formatCurrency(p.amount)}</span>
              </div>
            ))}
          </div>
        )}
        <p className="text-[11px]">Paid: {formatCurrency(invoice.paid)}</p>
        {invoice.balance > 0 ? (
          <p className="text-[11px] font-bold">Balance: {formatCurrency(invoice.balance)}</p>
        ) : (
          <p className="text-[11px] font-bold">PAID IN FULL</p>
        )}
      </div>
      <p className="text-center text-[10px] mt-3 pt-2 border-t border-dashed border-gray-400">
        {shop.footer}
      </p>
    </div>
  );
}

export function A4Invoice({ invoice, shop }: { invoice: InvoiceData; shop: ShopDetails }) {
  const rx = invoice.prescription;
  return (
    <div className="a4-invoice bg-white text-black rounded-lg p-6 shadow-lg text-base">
      <div className="flex justify-between items-center pb-4 border-b-2 border-[#6d5ef0]">
        <img src="/eyespy-logo-black.png" alt={shop.name} className="h-12 w-auto" />
        <div className="text-right">
          <p className="text-2xl font-extrabold tracking-wide text-[#6d5ef0]">INVOICE</p>
          <p className="text-sm text-gray-600">{invoice.invoiceNo}</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4 py-4 border-b border-gray-200 text-sm">
        <div>
          <p className="text-[10px] uppercase tracking-widest text-gray-400 mb-1">From</p>
          <p className="font-semibold">{shop.name}</p>
          {shop.address && <p className="text-gray-600">{shop.address}</p>}
          {shop.phone && <p className="text-gray-600">Ph: {shop.phone}</p>}
          {shop.ntn && <p className="text-gray-600">NTN: {shop.ntn}</p>}
        </div>
        <div>
          <p className="text-[10px] uppercase tracking-widest text-gray-400 mb-1">Billed To</p>
          <p className="font-semibold">{invoice.customerName ?? "Walk-in Customer"}</p>
          {invoice.customerPhone && <p className="text-gray-600">{invoice.customerPhone}</p>}
        </div>
        <div>
          <p className="text-[10px] uppercase tracking-widest text-gray-400 mb-1">Invoice Details</p>
          <p className="text-gray-600">Date: {invoice.date}</p>
          <p className="text-gray-600">Payment: {invoice.paymentMethod}</p>
          <p className="text-gray-600">Status: {invoice.paymentStatus}</p>
        </div>
      </div>

      {rx && (
        <div className="py-4 border-b border-gray-200">
          <p className="text-[10px] uppercase tracking-widest text-gray-400 mb-2">
            Prescription{rx.isOwn ? " (Customer's Own)" : ""}
          </p>
          <table className="w-full text-sm text-center">
            <thead>
              <tr className="bg-gray-100">
                <th className="py-1.5 pl-2 text-left font-semibold">Eye</th>
                <th className="font-semibold">SPH</th>
                <th className="font-semibold">CYL</th>
                <th className="font-semibold">AXIS</th>
                <th className="font-semibold">PD</th>
                <th className="font-semibold">ADD</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-100">
                <td className="py-1.5 pl-2 text-left">OD (Right)</td>
                <td>{v(rx.right.sph)}</td><td>{v(rx.right.cyl)}</td><td>{v(rx.right.axis)}</td><td>{v(rx.right.pd)}</td><td>{v(rx.right.add)}</td>
              </tr>
              <tr>
                <td className="py-1.5 pl-2 text-left">OS (Left)</td>
                <td>{v(rx.left.sph)}</td><td>{v(rx.left.cyl)}</td><td>{v(rx.left.axis)}</td><td>{v(rx.left.pd)}</td><td>{v(rx.left.add)}</td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      <table className="w-full text-sm my-4">
        <thead>
          <tr className="bg-gray-100 border-b-2 border-gray-300">
            <th className="text-left py-2 pl-2 w-8">#</th>
            <th className="text-left py-2">Item</th>
            <th className="text-center py-2">Qty</th>
            <th className="text-right py-2">Unit Price</th>
            <th className="text-right py-2">Discount</th>
            <th className="text-right py-2 pr-2">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.lines.map((line, i) => (
            <tr key={line.key} className="border-b border-gray-100 align-top">
              <td className="py-2 pl-2 text-gray-500">{i + 1}</td>
              <td className="py-2">
                {line.name}
                {line.description && <p className="text-xs text-gray-500 mt-0.5">{line.description}</p>}
              </td>
              <td className="text-center py-2">{line.quantity}</td>
              <td className="text-right py-2">{formatCurrency(line.unitPrice)}</td>
              <td className="text-right py-2">{line.discount > 0 ? `-${formatCurrency(line.discount)}` : "—"}</td>
              <td className="text-right py-2 pr-2">{formatCurrency(line.total)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="flex justify-end">
        <div className="w-64 text-sm space-y-1">
          <div className="flex justify-between"><span className="text-gray-600">Subtotal</span><span>{formatCurrency(invoice.subtotal)}</span></div>
          {invoice.discount > 0 && (
            <div className="flex justify-between"><span className="text-gray-600">Invoice Discount</span><span>-{formatCurrency(invoice.discount)}</span></div>
          )}
          <div className="flex justify-between text-lg font-bold border-t-2 border-gray-800 pt-2 mt-2">
            <span>Total</span><span className="text-[#6d5ef0]">{formatCurrency(invoice.total)}</span>
          </div>
          {(invoice.payments?.length ?? 0) > 0 && (
            <div className="border-t border-gray-200 pt-1 mt-1 text-xs text-gray-600">
              <div className="flex justify-between">
                <span>Advance ({invoice.paymentMethod})</span>
                <span>{formatCurrency(invoice.paid - invoice.payments!.reduce((s, p) => s + p.amount, 0))}</span>
              </div>
              {invoice.payments!.map((p, i) => (
                <div key={i} className="flex justify-between">
                  <span>{new Date(p.date).toLocaleDateString("en-PK", { day: "2-digit", month: "short", year: "numeric" })} ({p.method})</span>
                  <span>{formatCurrency(p.amount)}</span>
                </div>
              ))}
            </div>
          )}
          {invoice.balance > 0 ? (
            <>
              <div className="flex justify-between"><span className="text-gray-600">Paid</span><span>{formatCurrency(invoice.paid)}</span></div>
              <div className="flex justify-between font-semibold"><span>Balance Due</span><span>{formatCurrency(invoice.balance)}</span></div>
            </>
          ) : (
            <>
              <div className="flex justify-between"><span className="text-gray-600">Paid</span><span>{formatCurrency(invoice.paid)}</span></div>
              <div className="flex justify-between font-semibold text-[#16a34a]"><span>Paid in full</span><span>Rs.0 due</span></div>
            </>
          )}
        </div>
      </div>

      <div className="mt-8 pt-3 border-t border-gray-200 flex justify-between items-end text-xs text-gray-500">
        <div>
          {(invoice.orderTakenBy || invoice.billGeneratedBy) && (
            <p>Order taken by {invoice.orderTakenBy || "—"} · Bill generated by {invoice.billGeneratedBy || "—"}</p>
          )}
          <p className="mt-1">{shop.footer} Your vision is our mission.</p>
        </div>
        <p>Computer-generated invoice</p>
      </div>
    </div>
  );
}

/** The bill for a sale reopened from history. */
/** "Blue Cut · 1.56 index", the way the lens should read under its line. */
export function lensNote(lensColor: string, lensDescription: string) {
  return [lensColor, lensDescription].map((s) => s.trim()).filter(Boolean).join(" · ");
}

function withNote(description: string, note: string) {
  return [description, note].map((s) => s.trim()).filter(Boolean).join(" · ");
}

export function invoiceFromSale(sale: {
  invoiceNo: string; dateTime: string; customerId: string; customerName: string; customerPhone: string;
  createdByName: string; receivedByName: string;
  items: { id: string; productId: string; productName: string; description: string; quantity: number; unitPrice: number; discount: number; total: number }[];
  customLensName: string; customLensPrice: number;
  lensProductId: string; lensColor: string; lensDescription: string;
  subtotal: number; discount: number; total: number; paid: number; balance: number;
  paymentMethod: string; paymentStatus: string;
  payments: { date: string; amount: number; method: string }[];
  prescription: { rightEye: InvoicePrescription["right"]; leftEye: InvoicePrescription["left"]; isOwnPrescription: boolean } | null;
}): InvoiceData {
  // Colour and description belong to whichever lens was sold, so they print
  // under that line rather than as a stray note at the bottom.
  const note = lensNote(sale.lensColor, sale.lensDescription);
  const lines: InvoiceLine[] = sale.items.map((it) => ({
    key: it.id, name: it.productName,
    description: it.productId && it.productId === sale.lensProductId ? withNote(it.description, note) : it.description,
    quantity: it.quantity, unitPrice: it.unitPrice, discount: it.discount, total: it.total,
  }));
  if (sale.customLensPrice > 0) {
    lines.push({
      key: "custom-lens", name: sale.customLensName, description: note, quantity: 1,
      unitPrice: sale.customLensPrice, discount: 0, total: sale.customLensPrice,
    });
  } else if (note && !sale.lensProductId) {
    // A lens noted without a line of its own (colour recorded against the job).
    lines.push({ key: "lens-note", name: "Lens", description: note, quantity: 1, unitPrice: 0, discount: 0, total: 0 });
  }
  return {
    invoiceNo: sale.invoiceNo,
    date: new Date(sale.dateTime).toLocaleString("en-PK", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }),
    orderTakenBy: sale.createdByName,
    billGeneratedBy: sale.receivedByName,
    customerName: sale.customerId ? sale.customerName : null,
    customerPhone: sale.customerPhone,
    lines,
    subtotal: sale.subtotal,
    discount: sale.discount,
    total: sale.total,
    paymentMethod: sale.paymentMethod,
    paymentStatus: sale.paymentStatus,
    paid: sale.paid,
    balance: sale.balance,
    payments: sale.payments,
    prescription: sale.prescription
      ? { right: sale.prescription.rightEye, left: sale.prescription.leftEye, isOwn: sale.prescription.isOwnPrescription }
      : null,
  };
}

export function shopDetailsFromSettings(settings: { name: string; address: string; phone: string; ntn: string; receiptFooter: string }): ShopDetails {
  return {
    name: settings.name,
    address: settings.address,
    phone: settings.phone,
    ntn: settings.ntn,
    footer: settings.receiptFooter || `Thank you for choosing ${settings.name}!`,
  };
}
